from __future__ import annotations

import math


_NA = "Not available for the selected event."

_DISCLAIMER_TEXT = (
    "This summary is a screening-level monitoring interpretation generated by PierWatch, "
    "a decision-support prototype for engineering-informed SHM analytics. It does not replace "
    "field measurements, structural analysis, bridge inspection, or engineering judgment. "
    "Movement values are event-based screening estimates derived from the standalone GPS Data sheet. "
    "The primary monitoring device sheets (W2, PP 15, E2, E3 in the R1 workbook) "
    "provide jointmeter and temperature data for trend context. "
    "Risk assessments are scenario-based projections, not structural safety determinations."
)

SUMMARY_KEYS = [
    "executive_summary",
    "low_water_summary",
    "pier_movement_summary",
    "coupling_summary",
    "pp15_risk_summary",
    "sensitivity_summary",
    "thermal_context_summary",
    "sensor_confidence_summary",
    "recommended_next_steps",
    "disclaimer",
    "full_summary_text",
]


# ── Formatting helpers ────────────────────────────────────────────────────────

def _fmt(val, fmt: str = ".2f", unit: str = "", na: str = "N/A") -> str:
    """Return a safely formatted string for a possibly-None/NaN numeric value."""
    try:
        if val is None:
            return na
        f = float(val)
        if math.isnan(f) or math.isinf(f):
            return na
        return f"{f:{fmt}}{unit}"
    except (TypeError, ValueError):
        return na


def _get_pier_movement(movement_rows: list[dict], pier: str) -> float | None:
    """Extract longitudinal_movement_in for a specific pier from event movement rows."""
    target = pier.upper().replace("-", "")
    for row in movement_rows:
        pid = str(row.get("pier_id", "")).upper().replace("-", "")
        if pid == target:
            val = row.get("longitudinal_movement_in")
            try:
                f = float(val)  # type: ignore[arg-type]
                if not math.isnan(f):
                    return f
            except (TypeError, ValueError):
                pass
    return None


# ── Section generators ────────────────────────────────────────────────────────

def _section_low_water(event: dict) -> str:
    lwsi_line = ""
    lwsi = event.get("LWSI")
    if lwsi is not None:
        lwsi_line = f"\n  LWSI                    : {_fmt(lwsi, '.3f')}"

    return (
        f"  Event ID                : {event.get('event_id', 'N/A')}\n"
        f"  Start date              : {event.get('start_date', 'N/A')}\n"
        f"  End date                : {event.get('end_date', 'N/A')}\n"
        f"  Duration                : {_fmt(event.get('duration_days'), '.0f', ' days')}\n"
        f"  Min. river stage        : {_fmt(event.get('min_stage_ft'), '.2f', ' ft')}\n"
        f"  Days below 12 ft        : {_fmt(event.get('days_below_12'), '.0f')}\n"
        f"  Days below 7 ft         : {_fmt(event.get('days_below_7'), '.0f')}\n"
        f"  Cumul. deficit (<7 ft)  : {_fmt(event.get('cumulative_deficit_below_7'), '.2f', ' ft·day')}\n"
        f"  Event class             : {event.get('event_class', 'N/A')}"
        f"{lwsi_line}"
    )


def _section_pier_movement(movement_rows: list[dict]) -> str:
    e1 = _get_pier_movement(movement_rows, "E1")
    e2 = _get_pier_movement(movement_rows, "E2")
    e3 = _get_pier_movement(movement_rows, "E3")

    def _mov_str(v: float | None) -> str:
        return _fmt(v, ".3f", " in") if v is not None else "Insufficient GPS data"

    return (
        "GPS-derived pier movement estimates (longitudinal):\n"
        f"  Pier E-1  : {_mov_str(e1)}\n"
        f"  Pier E-2  : {_mov_str(e2)}\n"
        f"  Pier E-3  : {_mov_str(e3)}\n\n"
        "Values are event-based screening estimates computed from median pre-event and "
        "post-event GPS position windows. GPS monitoring began in June 2022; events prior "
        "to this date have no GPS-derived movement estimates. Positive longitudinal values "
        "indicate movement toward the channel (westward)."
    )


def _section_coupling(coupling: dict) -> str:
    status = coupling.get("coupling_status", "N/A")
    interp = coupling.get("interpretation", "")
    return (
        f"  Coupling status (E-1/E-2) : {status}\n"
        f"  Coupling ratio (E1÷E2)    : {_fmt(coupling.get('coupling_ratio'), '.3f')}\n"
        f"  Differential movement     : {_fmt(coupling.get('differential_movement_in'), '.3f', ' in')}\n"
        f"  Average absolute movement : {_fmt(coupling.get('average_abs_movement_in'), '.3f', ' in')}\n"
        f"  Movement tolerance used   : {_fmt(coupling.get('tolerance_in'), '.3f', ' in')}\n\n"
        f"  Interpretation: {interp}"
    )


def _section_pp15_risk(risk: dict) -> str:
    return (
        f"  Remaining allowable movement (input)  : {_fmt(risk.get('remaining_allowable_in'), '.3f', ' in')}\n"
        f"  Predicted additional movement         : {_fmt(risk.get('predicted_additional_movement_in'), '.3f', ' in')}\n"
        f"  Remaining after scenario              : {_fmt(risk.get('remaining_after_scenario_in'), '.3f', ' in')}\n"
        f"  Risk ratio                            : {_fmt(risk.get('risk_ratio'), '.3f')}\n"
        f"  Risk level                            : {risk.get('risk_level', 'N/A')}\n"
        f"  Recommended action                    : {risk.get('recommendation', 'N/A')}\n\n"
        "This PP-15 joint clearance risk assessment is a scenario-based screening projection. "
        "It uses an assumed movement rate and a user-supplied remaining allowance estimate, "
        "not real-time joint clearance field measurements. "
        "A 'Span Jacking Likely' result is a screening-level trigger for engineering review, "
        "not a structural safety determination."
    )


def _section_sensitivity(sensitivity: dict) -> str:
    event_id = sensitivity.get("event_id", "N/A")
    year = sensitivity.get("event_year", "N/A")
    return (
        f"  Event              : {event_id} ({year})\n"
        f"  LWSI               : {_fmt(sensitivity.get('LWSI'), '.3f')}\n"
        f"  E1 longitudinal    : {_fmt(sensitivity.get('E1_longitudinal_movement_in'), '.3f', ' in')}\n"
        f"  E2 longitudinal    : {_fmt(sensitivity.get('E2_longitudinal_movement_in'), '.3f', ' in')}\n"
        f"  E1 movement/LWSI   : {_fmt(sensitivity.get('E1_movement_per_LWSI'), '.3f', ' in/LWSI')}\n"
        f"  E2 movement/LWSI   : {_fmt(sensitivity.get('E2_movement_per_LWSI'), '.3f', ' in/LWSI')}\n\n"
        "Low-water exposure severity and pier movement are not necessarily a simple linear "
        "relationship. The 2022 event (LW-050) is treated as a high-movement reference event. "
        "Later events show lower movement sensitivity even under significant low-water exposure, "
        "which may reflect hysteresis, soil-pier interaction history, prior movement state, or "
        "remediation effects. Year-to-year sensitivity comparison requires continued monitoring data."
    )


def _section_thermal(thermal_stats: dict) -> str:
    r2 = thermal_stats.get("r_squared")
    slope = thermal_stats.get("slope")
    status = thermal_stats.get("status", "unknown")
    n = thermal_stats.get("record_count", 0)

    r2_str = _fmt(r2, ".3f")
    r2_pct = f"{float(r2) * 100:.1f}%" if r2 is not None and not math.isnan(float(r2)) else "N/A"

    lines = [
        "PP-15 linear thermal correction (measured expansion ~ temperature):",
        f"  Model status   : {status}",
        f"  Records used   : {n}",
        f"  Slope          : {_fmt(slope, '.4f', ' in/°F')}",
        f"  R²             : {r2_str}  ({r2_pct} of measured-expansion variance explained by temperature)",
        "",
    ]

    if status == "ok" and r2 is not None:
        try:
            if float(r2) < 0.30:
                lines.append(
                    "The relatively low R² indicates that non-thermal factors — structural movement, "
                    "span jacking history, or sensor effects — dominate the PP-15 record."
                )
        except (ValueError, TypeError):
            pass

    lines.extend([
        "",
        "PP-15 thermal context uses the primary PP 15 device sheet (R1), which covers the full "
        "monitoring record. Year-over-year comparison "
        "under similar thermal conditions requires multiple seasons of records. "
        "This thermal correction analysis supports screening-level interpretation; it does not "
        "fully isolate structural movement from other sources of variance.",
    ])
    return "\n".join(lines)


def _section_sensor_confidence(quality_summary: dict) -> str:
    n_high = quality_summary.get("n_high", 0)
    n_medium = quality_summary.get("n_medium", 0)
    n_low = quality_summary.get("n_low", 0)
    n_poor = quality_summary.get("n_poor", 0)
    n_insuf = quality_summary.get("n_insufficient", 0)
    n_total = quality_summary.get("n_total", 0)
    avg = quality_summary.get("avg_confidence_score")

    return (
        f"  Total streams assessed   : {n_total}\n"
        f"  High confidence          : {n_high}\n"
        f"  Medium confidence        : {n_medium}\n"
        f"  Low / Poor               : {n_low + n_poor}\n"
        f"  Insufficient Data        : {n_insuf}\n"
        f"  Average confidence score : {_fmt(avg, '.3f')}\n\n"
        "Confidence score formula: 0.40 × completeness + 0.25 × recent availability + "
        "0.20 × (1 − outlier rate) + 0.15 × (1 − missing rate). "
        "A high confidence score indicates good data completeness and low error rates. "
        "It does not prove sensor correctness. Manual data validation and field verification "
        "remain essential before drawing structural conclusions."
    )


def _section_recommended_steps(
    event: dict,
    coupling_row: dict | None,
    pp15_risk_result: dict | None,
) -> str:
    steps = [
        "1. Continue monitoring river stage and GPS pier positions during future low-water periods.",
        "2. Review PP-15 joint clearance against field measurements before and after each event.",
        "3. Compare GPS-derived movement estimates with jointmeter readings and recent inspections.",
        "4. Treat high-risk PP-15 scenario outputs as screening-level triggers for engineering "
           "review, not structural safety determinations.",
        "5. Use future monitoring data to refine event sensitivity metrics and thermal correction "
           "interpretation as additional years of records become available.",
    ]

    if coupling_row and coupling_row.get("coupling_status") == "Coupled":
        steps.append(
            "6. E-1/E-2 coupled movement was detected for this event. "
               "Verify lateral pier positions with field survey data."
        )

    if pp15_risk_result:
        level = pp15_risk_result.get("risk_level", "")
        if level in ("Critical", "Span Jacking Likely"):
            steps.append(
                f"7. PP-15 screening scenario risk level is '{level}'. "
                   "Coordinate with bridge engineering team and review span-jacking contingency plan."
            )

    event_class = event.get("event_class", "")
    if "2022" in str(event_class) or "Critical" in str(event_class):
        steps.append(
            "8. This event is classified as Critical / 2022-like. Treat all screening outputs "
               "with heightened caution and prioritise field verification."
        )

    return "\n".join(steps)


# ── Main function ─────────────────────────────────────────────────────────────

def generate_engineering_summary(
    selected_event_row: dict | None = None,
    movement_rows: list[dict] | None = None,
    coupling_row: dict | None = None,
    pp15_risk_result: dict | None = None,
    sensitivity_row: dict | None = None,
    sensor_quality_summary: dict | None = None,
    pp15_thermal_stats: dict | None = None,
    include_disclaimer: bool = True,
) -> dict:
    """Generate a screening-level engineering monitoring summary.

    All inputs are optional; missing inputs produce graceful 'not available' text
    rather than errors.

    Returns a dict with keys defined in SUMMARY_KEYS.
    """
    out: dict[str, str] = {k: _NA for k in SUMMARY_KEYS}
    out["disclaimer"] = _DISCLAIMER_TEXT if include_disclaimer else ""

    if not selected_event_row:
        msg = (
            "No event selected. "
            "Please select a low-water event to generate an engineering monitoring summary."
        )
        out["executive_summary"] = msg
        out["full_summary_text"] = msg
        return out

    event = selected_event_row
    event_id = str(event.get("event_id", "N/A"))
    event_year = str(event.get("event_year", "N/A"))

    # ── Individual sections ───────────────────────────────────────────────────
    out["low_water_summary"] = _section_low_water(event)

    if movement_rows is not None:
        out["pier_movement_summary"] = _section_pier_movement(movement_rows)

    if coupling_row:
        out["coupling_summary"] = _section_coupling(coupling_row)

    if pp15_risk_result:
        out["pp15_risk_summary"] = _section_pp15_risk(pp15_risk_result)

    if sensitivity_row:
        out["sensitivity_summary"] = _section_sensitivity(sensitivity_row)

    if pp15_thermal_stats:
        out["thermal_context_summary"] = _section_thermal(pp15_thermal_stats)

    if sensor_quality_summary:
        out["sensor_confidence_summary"] = _section_sensor_confidence(sensor_quality_summary)

    out["recommended_next_steps"] = _section_recommended_steps(
        event, coupling_row, pp15_risk_result
    )

    # ── Executive summary ─────────────────────────────────────────────────────
    e1 = _get_pier_movement(movement_rows or [], "E1")
    e2 = _get_pier_movement(movement_rows or [], "E2")
    risk_level = pp15_risk_result.get("risk_level", "N/A") if pp15_risk_result else "N/A"
    risk_rec = pp15_risk_result.get("recommendation", "") if pp15_risk_result else ""
    coupling_status = coupling_row.get("coupling_status", "") if coupling_row else ""

    exec_parts = [
        f"Event {event_id} ({event_year}) was a {event.get('event_class', 'low-water')} event "
        f"from {event.get('start_date')} to {event.get('end_date')} "
        f"({_fmt(event.get('duration_days'), '.0f')} days). "
        f"Minimum river stage: {_fmt(event.get('min_stage_ft'), '.2f')} ft "
        f"({_fmt(event.get('days_below_7'), '.0f')} days below 7 ft)."
    ]

    if e1 is not None or e2 is not None:
        exec_parts.append(
            f"GPS-derived movement: E-1 = {_fmt(e1, '.3f', ' in')}, "
            f"E-2 = {_fmt(e2, '.3f', ' in')}."
        )
    else:
        exec_parts.append("GPS-derived movement: not available for this event.")

    if coupling_status:
        exec_parts.append(f"E-1/E-2 coupling: {coupling_status}.")

    if pp15_risk_result:
        exec_parts.append(f"PP-15 screening risk: {risk_level}. {risk_rec}")

    out["executive_summary"] = " ".join(exec_parts)

    # ── Full summary text ─────────────────────────────────────────────────────
    header = (
        "PierWatch Engineering Monitoring Summary\n"
        "Screening-Level Decision-Support Prototype — Not an Official Engineering Report\n"
        + "=" * 70
    )

    def _block(title: str, body: str) -> str:
        return f"[{title}]\n{body}"

    blocks = [
        header,
        _block("EXECUTIVE SUMMARY", out["executive_summary"]),
        _block("LOW-WATER EVENT", out["low_water_summary"]),
        _block("PIER MOVEMENT", out["pier_movement_summary"]),
        _block("E-1 / E-2 COUPLING", out["coupling_summary"]),
        _block("PP-15 JOINT CLEARANCE RISK SCENARIO", out["pp15_risk_summary"]),
        _block("YEAR-TO-YEAR SENSITIVITY CONTEXT", out["sensitivity_summary"]),
        _block("THERMAL CORRECTION CONTEXT", out["thermal_context_summary"]),
        _block("SENSOR CONFIDENCE", out["sensor_confidence_summary"]),
        _block("RECOMMENDED NEXT STEPS", out["recommended_next_steps"]),
    ]
    if include_disclaimer:
        blocks.append(_block("DISCLAIMER", out["disclaimer"]))

    out["full_summary_text"] = "\n\n".join(blocks)
    return out
